<?php

namespace Ennva\WebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubpagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubpagesRepository extends EntityRepository
{
	public function findSubpagesByIdPage($options = array())
	{
		$qb = $this->createQueryBuilder('s');
		
		if($options['id']){
			$qb->where('s.page_id = :id')
			   ->setParameter('id', $options['id'])
			;
		}
		
		$query = $qb->getQuery();
		
		return $query->getResult();
		
	}
}
