ennva_ecommerce:
    resource: "@EnnvaEcommerceBundle/Controller/"
    type:     annotation
    prefix:   /

ennva_website:
    resource: "@EnnvaWebsiteBundle/Controller/"
    type:     annotation
    prefix:   /
